[package]
name = "hoa-tcms-core"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
hoa-tcms-pkg = { path = "../pkg" }

actix-web.workspace = true
actix-files.workspace = true
actix-multipart.workspace = true
mime.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
tracing.workspace = true
futures-util.workspace = true
sqlx.workspace = true
sea-orm.workspace = true
redis.workspace = true
tokio.workspace = true
config.workspace = true
pbkdf2.workspace = true
hmac.workspace = true
sha2.workspace = true
password-hash.workspace = true
rand.workspace = true
actix-session.workspace = true
async-trait.workspace = true
base64.workspace = true
serde_yaml.workspace = true

[lib]
name = "hoa_tcms_core"
path = "lib.rs"
