[package]
name = "hoa-tcms-server"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
hoa-tcms-core = { path = "../../internal" }
hoa-tcms-pkg = { path = "../../pkg" }

actix-web.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
sqlx.workspace = true
redis.workspace = true
actix-session.workspace = true
sea-orm.workspace = true

[[bin]]
name = "server"
path = "main.rs"
